config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ sessions: 'users/sessions', registrations: 'users/registrations', passwords:'users/passwords'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :publications

  get '/home', to: 'main#home', as: 'home'

  get '/about', to: 'main#about', as: 'about'

  get '/servicios', to: 'main#services', as: 'services'

  get '/contacto', to: 'main#contact', as: 'contact'

  root 'main#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
  mount_uploader :cover, CoverUploader
  validates :title, presence: { message: "La publicación debe tener titulo."}
  validates :title, length: {minimum: 12, maximum: 150, too_long: "Titulo muy largo (%{count} carácteres máximo).", too_short: "Titulo muy corto (%{count} carácteres mínimo)."}
  validates :body, presence: {message: "La publicación debe tener cuerpo."}
  validates :body,  length:{minimum: 50, too_short:"Cuerpo muy corto (%{count} carácteres mínimo)"}
  validates :cover, presence: {message: "La publicación debe tener una portada."};
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @news = Publication.order('created_at DESC').first(5)
  end

  def about

  end

  def services

  end

  def contact

  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, only:[:edit, :update, :delete, :new, :create]

  def index
    @publications = Publication.all.order('created_at DESC')
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)
    if(@publication.save)
      redirect_to @publication
    else
      render 'new'
    end
  end

  def edit
    @publication = Publication.find(params[:id])
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def update
    @publication = Publication.find(params[:id])
    if(@publication.update_attributes(publication_params))
      flash[:notice] = "Publicacion editada correctamente"
      redirect_to @publication
    else
      render 'edit'
    end
  end

  def destroy
    publication = Publication.find(params[:id])
    publication.destroy
    redirect_to publications_path
  end

  def publication_params
    params.require(:publication).permit(:title, :body, :cover)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
   prepend_before_action :require_no_authentication, only: :cancel
   before_action :authenticate_user!
  # GET /resource/sign_up
  # def new
  #   super
  # end
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #def authenticate_user!(current_user)
  #  if(!user_signed_in?)
  #    redirect_to :new_user_session
  #  end
  #end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_user!, only: [:destroy]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/_nav-blue-menu.html.erb
<header id="header-mobile" class="row">
  <div id="menu-icons" class="row col-s-10  menu-icons">
    <div class="col-s-11">
      <%=link_to image_tag("logoAlexAzul.png", {alt: "Logo", class: 'burger-menu-logo'}), root_path%>
    </div>
    <div class="col-s-1 burger-button">
      <a href="javascript:void(0)" onclick="openNav()" id="blue-openbtn"><%=image_tag "menu-azul.png", alt:"Cerrar menú", class:"social-icon"%></a>
    </div>
  </div>
  <div id="my-sidenav" class="row sidenav">
    <div class="row menu-icons">
      <div class="row col-s-10 ">
        <div class="col-s-11">
          <%=link_to image_tag('logoAlex.png', {alt:'Logo de alex', class: 'burger-menu-logo'}), :root%>
        </div>
        <div class="col-s-1 burger-button">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav();"><%=image_tag "cancel-cross.png", alt:"Cerrar menú", class:"social-icon"%></a>
        </div>
      </div>
    </div>

    <div id="nav-links" class="row">
      <div class="col-s-10">
        <%=link_to "INICIO", root_path%>
        <%=link_to "SERVICIOS", services_path%>
        <%=link_to "SOBRE NOSOTROS", about_path%>
        <%=link_to "NOTICIAS", publications_path%>
        <%=link_to "CONTACTO", contact_path%>
        <%if user_signed_in?%>
        <%=link_to "REGISTRAR USUARIO", new_user_registration_path%>
        <%=link_to "PUBLICAR", new_publication_path%>
        <%=link_to "CUENTA".upcase, edit_user_registration_path%>
        <%=link_to "CERRAR SESIÓN", destroy_user_session_path, method: 'delete'%>
        <%end%>
      </div>
    </div>
  <!--  <div class="row">
      <div class="">
        <a href="facebook.com"><%=image_tag 'facebook-logo.png', alt:'Enlace a Facebook', class:'social-icon'%></a>
      </div>
    </div>-->
    <div class="row social-media-menu">
      <div class=" col-s-10">
        <div class="col-s-11">
          <ul>
            <li>
              <%= link_to image_tag('facebook-logo.png',{alt:'Enlace a Facebook', class:'social-icon'}), "https://www.facebook.com/aireacondicionadouruguay/"%>
            </li>
            <li>
              <%= link_to image_tag('twitter-logo.png',{alt:'Enlace a Twitter', class:'social-icon'}), "https://twitter.com/airealex1"%>
            </li>
            <li>
              <%= link_to image_tag('instagram-logo.png',{alt:'Enlace a Instagram', class:'social-icon'}), "https://www.instagram.com/aireacondicionadoalex/"%>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</header>
<header id="header-desktop" class="row">
  <div class="sidenav-desktop sidenav-desktop-blue row">
    <div class="col-md-11 row">
      <div class="col-md-1">
            <%=link_to image_tag('logoAlexAzul.png', {alt:'Logo de alex', class: 'logo-image'}), :root %>
      </div>

      <div class="col-md-11 nav-links-blue">
        <ul>
          <%if user_signed_in? %>
          <div class="dropdown">
            <%= link_to "USUARIO", edit_user_registration_path, class:"dropbtn" %>
            <div class="dropdown-content content-blue">
              <%=link_to "REGISTRAR USUARIO", new_user_registration_path%>
              <%=link_to "PUBLICAR", new_publication_path%>
              <%=link_to "CUENTA", edit_user_registration_path%>
              <%=link_to "CERRAR SESIÓN", destroy_user_session_path, method: 'delete'%>
            </div>
          </div>
          <%end%>
          <li><%=link_to "SERVICIOS", services_path%></li>
          <li><%=link_to "SOBRE NOSOTROS", about_path%></li>
          <li><%=link_to "NOTICIAS", publications_path%></li>
          <li><%=link_to "CONTACTO", contact_path%></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_nav-menu.html.erb
<header id="header-mobile">
  <a href="javascript:void(0)" id="openbtn" onclick="openNav()">&#9776;</a>

  <div id="my-sidenav" class="row sidenav">
    <div class="row menu-icons">
      <div class="row col-s-10 ">
        <div class="col-s-11">
          <%=link_to image_tag('logoAlex.png', {alt:'Logo de alex', class: 'burger-menu-logo'}), :root%>
        </div>
        <div class="col-s-1 burger-button">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav();"><%=image_tag "cancel-cross.png", alt:"Cerrar menú", class:"social-icon"%></a>
        </div>
      </div>
    </div>

    <div id="nav-links" class="row">
      <div class="col-s-10">
        <%=link_to "INICIO", root_path%>
        <%=link_to "SERVICIOS", services_path%>
        <%=link_to "SOBRE NOSOTROS", about_path%>
        <%=link_to "NOTICIAS", publications_path%>
        <%=link_to "CONTACTO", contact_path%>
        <%if user_signed_in?%>
        <%=link_to "REGISTRAR USUARIO", new_user_registration_path%>
        <%=link_to "PUBLICAR", new_publication_path%>
        <%=link_to "CUENTA", edit_user_registration_path%>
        <%=link_to "CERRAR SESIÓN", destroy_user_session_path, method: 'delete'%>
        <%end%>
      </div>
    </div>
  <!--  <div class="row">
      <div class="">
        <a href="facebook.com"><%=image_tag 'facebook-logo.png', alt:'Enlace a Facebook', class:'social-icon'%></a>
      </div>
    </div>-->
    <div class="row social-media-menu">
      <div class=" col-s-10">
        <div class="col-s-11">
          <ul>
            <li>
              <%= link_to image_tag('facebook-logo.png',{alt:'Enlace a Facebook', class:'social-icon'}), "https://www.facebook.com/aireacondicionadouruguay/"%>
            </li>
            <li>
              <%= link_to image_tag('twitter-logo.png',{alt:'Enlace a Twitter', class:'social-icon'}), "https://twitter.com/airealex1"%>
            </li>
            <li>
              <%= link_to image_tag('instagram-logo.png',{alt:'Enlace a Instagram', class:'social-icon'}), "https://www.instagram.com/aireacondicionadoalex/"%>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</header>

<header id="header-desktop" class="row">
  <div class="sidenav-desktop row">
    <div class="col-md-11 row">
      <div class="col-md-1">
            <%=link_to image_tag('logoAlex.png', {alt:'Logo de alex', class: 'logo-image'}), :root %>
      </div>

      <div class="col-md-11 nav-links">
        <ul>
          <%if user_signed_in? %>
          <div class="dropdown">
            <%= link_to "USUARIO", edit_user_registration_path, class:"dropbtn" %>
            <div class="dropdown-content">
              <%=link_to "REGISTRAR USUARIO", new_user_registration_path%>
              <%=link_to "PUBLICAR", new_publication_path%>
              <%=link_to "CUENTA", edit_user_registration_path%>
              <%=link_to "CERRAR SESIÓN", destroy_user_session_path, method: 'delete'%>
            </div>
          </div>
          <%end%>
          <li><%=link_to "SERVICIOS", services_path%></li>
          <li><%=link_to "SOBRE NOSOTROS", about_path%></li>
          <li><%=link_to "NOTICIAS", publications_path%></li>
          <li><%=link_to "CONTACTO", contact_path%></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alex | <%=@title%></title>
    <meta name="description" content="Alex es una empresa de instalacion y venta de aire acondicionado e instalaciones electricas con mas de .. años de experiencia.">
    <meta name="keywords" content="Electricidad,Electricista,Montevideo,Uruguay,Corriente,Aire,Acondicionado,Frio,Calor,Alex,Alexander">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%=favicon_link_tag 'logoCuadrado.png'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="row">
    <%if action_name == "home" %>
      <%= render 'layouts/nav-menu'%>
    <%else%>
      <%=render 'layouts/nav-blue-menu' %>
    <%end %>
    <%= yield %>

    <footer id="footer" class="row">
      <div class="col-s-12 col-md-12">
        <hr class="separador-footer">
      </div>
      <div id ="social-media" class ="row col-s-10 col-md-11">
        <div class="col-s-9 footer-logo-wrapper"  >
          <%=link_to image_tag('logoAlexAzul.png', {alt:'Logo de alex', class: 'footer-logo-image'}), :root%>
          </br>
          <%=link_to image_tag('user.png', {alt:'Ingresar', class:'social-icon'}), :new_user_session%>
        </div>

        <div class="col-md-6 mail-footer">
          <p><span><%=link_to image_tag('user.png', {alt:'Ingresar', class:'social-icon'}), :new_user_session%></span>    airealexmontevideo@gmail.com</p>

        </div>

        <div class="col-s-3 col-md-6 footer-social-wrapper">
          <ul>
            <li><a href="https://www.facebook.com/aireacondicionadouruguay/">Facebook</a></li>
            <li><a href="https://twitter.com/airealex1">Twitter</a></li>
            <li><a href="https://www.instagram.com/aireacondicionadoalex/">Instagram</a></li>
          </ul>

        </div>
      </div>
    </footer>
  </body>

app/views/main/about.html.erb
<%@title = "Sobre nosotros"%>
<article class="desktop-wrapper col-s-10 col-md-11">
  <hr class="separador-desktop">
  <div class="content-wrapper row">
    <div class="title-wrapper col-s-12 col-md-6">
      <h1>Sobre Alex</h1>
      <hr class="separador-mobile">
    </div>
    <div class="body-text col-s-12  col-md-6">
      <p>Somos una empresa familiar con base en Montevideo dedicada a la venta y servicios de aire acondicionado, y a la electricidad en general. Contamos con más de 10 años de experiencia, desempeñándonos bajo la firma autorizada de UTE.
Nuestro objetivo es solucionar los problemas de climatización y electricidad mediante un servicio de calidad que transmite confianza.</p>
    </div>
  </div>

</article>

app/views/main/contact.html.erb
<%@title = "Contacto"%>
<article class="row desktop-wrapper">
  <div class="photo-slider-img-wrapper mobile-contact-cover">
    <%=image_tag "Imagen-noticia.jpg", alt: "imagen alex", class: "photo-slider-img"%>
  </div>
  <div class="col-s-10 col-md-11">
    <div class="title-wrapper" style="margin-top:6vh;">
      <hr class="separador-desktop">
      <h1>Contacto</h1>
      <hr class="separador-mobile">
    </div>
    <div class="content-wrapper cold-md-11 row">
      <div class="col-md-6 desktop-contact-img">
        <div class=" services-img-wrapper">
            <%=image_tag "contacto.png", alt: "imagen alex", class: "photo-slider-img"%>
        </div>
      </div>
      <div class="col-md-1"><!--separador--></div>
      <div class="col-md-5 col-s-12">
        <p class="body-text">Celular: 095938342</p>
        <p class="body-text">Telefono: 23119708</p>
        <p class="body-text">E-mail: airealexmontevideo@gmail.com</p>
        <p class="body-text contact-links"><a href="https://www.facebook.com/aireacondicionadouruguay/">Facebook</a></p>
        <p class="body-text contact-links"><a href="https://twitter.com/airealex1">Twitter</a></p>
        <p class="body-text contact-links"><a href="https://www.instagram.com/aireacondicionadoalex/">Instagram</a></p>
      </div>
    </div>
  </div>
</article>

app/views/main/home.html.erb
<%@title = "Inicio"%>
<section class="row">
  <div id="cover" class="cover col-s-12 row">
    <div id="icon">
      <%=image_tag 'logoAlex.png', alt:'Logo de alex', class: 'logo-image' %>
    </div>
    <div id="arrow-cover">
      <%=image_tag 'arrow.gif', alt:'Indicador', id: 'slide-arrow' %>
    </div>
  </div>
  <div class="button-call-desktop">
    <%=link_to "Llamar", contact_path, class: 'admin-button' %>
  </div>
  <div class="button-call-mobile row col-s-11">
    <a href="tel:+59895938342" class="admin-button col-s-3">Llamar</a>
  </div>
  <hr class="separador-desktop">
  <div class="col-s-12 col-md-12 row content-wrapper content-wrapper-desktop">
    <div class="col-s-10 col-md-11"><p class="home-text">Alex es una empresa dedicada a la electricidad en general y a la instalación, reparación y mantenimiento de equipos de aire acondicionado.</p></div>
    <div id="button" class="col-s-10 col-md-11 button-wrapper"><%=link_to 'SABER MÁS', about_path , class: "button"%></div>

  </div>

    <div class=" row slideshow-container">
      <%@news.each do |publ| %>
        <div class="row publ-container col-s-12 col-md-12 mySlides fade">
          <div class="photo-slider-img-wrapper">
            <div class="numbertext"><%="#{@news.index(publ)+1}/#{@news.size}"%></div>
            <%=link_to image_tag(publ.cover.url, {class:"photo-slider-img"}), publication_path(publ) %>
            <%= link_to publication_path(publ), class: "publ-title" do%>
              <div>
                <p><%=publ.title.upcase%></p>
              </div>
            <%end%>
          </div>

        </div>
      <%end%>
            <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    <div style="text-align:center; background-color: #307FE2; item-align:center" class="row col-s-12 col-md-12">
      <%@news.each do |publ|%>
      <span class="dot" onclick="currentSlide(<%=@news.index(publ)+1%>)"></span>
      <%end%>
    </div>
</section>

<script type="text/JavaScript">
  showSlides(1);
</script>

app/views/main/services.html.erb
<%@title = "Servicios"%>
<article class="desktop-wrapper content-wrapper row">
  <div class="title-wrapper col-s-10 col-md-11">
    <hr class="separador-desktop">
    <h1>Servicios</h1>
    <hr class="separador-mobile">
  </div>

  <div class="col-s-10 col-md-11 row service-items">
    <div class="col-md-6 col-s-12 row">
        <div class="services-img-wrapper">
          <%=image_tag("aire.png", class:"photo-slider-img")%>
        </div>
    </div>
    <div class="col-md-1"><!--separador--></div>
    <div class="content-wrapper services-body col-md-5">
      <h2>AIRE ACONDICIONADO</h2>
      <div>
        <p class="body-text">Realizamos instalación, mantenimiento y reparación de equipos de aire acondicionado. La instalación es con bomba de vacio, como recomienda el fabricante.</p>
      </div>
      <div class="button-wrapper">
        <a href="tel:+59895938342" class="button">LLAMAR</a>
      </div>
    </div>
    <hr class="separador-desktop col-md-12">
    <div class="col-md-6 col-s-12 row">
      <div class="services-img-wrapper">
        <%=image_tag("electricidad.png", class:"photo-slider-img")%>
      </div>
    </div>
    <div class="col-md-1"><!--separador--></div>
    <div class="content-wrapper services-body col-md-5">
      <h2>ELECTRICIDAD</h2>
      <div>
        <p class="body-text">Ofrecemos un servicio profesional, bajo la firma autorizada por UTE. Realizamos instalaciones completas. Trabajamos con megómetro, para la localización de fugas. Reciclaje de tableros eléctricos y más.</p>
      </div>
      <div class="button-wrapper">
        <a href="tel:+59895938342" class="button">LLAMAR</a>
      </div>
    </div>

    <hr class="separador-desktop col-md-12">
    <div class="col-md-6 col-s-12 row">
      <div class="services-img-wrapper">
        <%=image_tag("Imagen-noticia.jpg", class:"photo-slider-img")%>
      </div>
    </div>
    <div class="col-md-1"><!--separador--></div>
    <div class="content-wrapper services-body col-md-5">
      <h2>VENTA DE EQUIPOS</h2>
      <div>
        <p class="body-text">Tenemos a la venta equipos de aire acondicionado Gree con 1 año de garantía. <br> Estos equipos tienen categoría energética A y utiliza gases ecológicos, lo que conlleva a un bajo consumo enérgetico.</p>
      </div>
      <div class="button-wrapper">
        <a href="tel:+59895938342" class="button">LLAMAR</a>
      </div>
    </div>
  </div>

</article>

app/views/publications/index.html.erb
<%@title = "Noticias"%>
<section class=" desktop-wrapper content-wrapper row">
  <div class="title-wrapper col-s-10 col-md-11">
    <hr class="separador-desktop">
    <h1>Noticias</h1>
    <hr class="separador-mobile">
  </div>

  <div class="row col-md-11 publications">
    <%@publications.each do |publ| %>
      <div class="row col-md-5 publication">
        <div class="col-s-10 col-md-12">
          <p class="publ-list-title-date"><%= publ.created_at.strftime("%d/%m/%Y") %></p>
        </div>
        <div class="row publ-container col-s-10 col-md-12">
          <div class="cover-news-img-wrapper">
            <%= link_to image_tag(publ.cover.url, {class: "photo-slider-img"}), publication_path(publ)%>
          </div>
        </div>
        <div class="publ-list-title-wrapper col-s-10 col-md-12">
          <p class="publ-list-title"><%=link_to publ.title.capitalize, publication_path(publ)%> <%=image_tag "link-arrow.png", alt: "link", class: "social-icon"%></p>
        </div>
      </div>
    <%end%>
  </div>

</section>

app/views/publications/show.html.erb
<%@title = @publication.title%>
<article class="row desktop-wrapper">
  <div class="col-s-12 photo-slider-img-wrapper publ-container mobile-contact-cover">
    <%=image_tag @publication.cover.url, {class:'photo-slider-img', alt:'Portada de la publicación'}%>
    <div class="publ-title"><h1><%=@publication.title.upcase %></h1></div>
  </div>

  <div class="col-md-11">
    <hr class="separador-desktop">
  </div>

  <div class="row col-md-11  content-wrapper">
    <div class="desktop-contact-img col-md-6">
      <div class=" services-img-wrapper">
        <%=image_tag @publication.cover.url, {class:'photo-slider-img', alt:'Portada de la publicación'}%>
      </div>
    </div>
    <div class="col-md-1"><!--Separador--></div>
    <div class="col-s-10 col-md-5 ">
      <h1 class="desktop-publ-title"><%=@publication.title%></h1> <br>
      <p class="body-text"><%=@publication.body%></p>
    </div>
    <div class="actions row col-md-11 col-s-12" style="margin-top: 5rem;">
      <%if user_signed_in?%>
        <%=link_to 'Editar publicación', edit_publication_path(@publication), class:"admin-button col-md-5"%>
        <div class="col-md-2"> <!--Separador--></div>
        <%=link_to 'Eliminar publicación', @publication, data: { confirm: "¿Estás seguro?" }, method: :delete, class:"admin-button col-md-5"%>
      <%end%>
    </div>
  </div>


</article>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar sesión", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "¿Olvidaste la contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>